In [ ]:
with open('/content/names.txt','r') as file:
  content = file.read().splitlines()

In [ ]:
print(content[:10])

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia', 'harper', 'evelyn']


In [ ]:
b= {}
for word in content[:1]:
  chs = ['<S>'] + list(word) + ['<E>']
  # print(chs[1:])
  for ch1, ch2 in zip(chs,chs[1:]):
    # print(ch1,ch2)
    biagram = (ch1,ch2)
    b[biagram] = b.get(biagram,0)+1
print(b)


{('<S>', 'e'): 1, ('e', 'm'): 1, ('m', 'm'): 1, ('m', 'a'): 1, ('a', '<E>'): 1}


In [ ]:
b= {}
for word in content:
  chs = ['.'] + list(word) + ['.']
  # print(chs[1:])
  for ch1, ch2 in zip(chs,chs[1:]):
    # print(ch1,ch2)
    biagram = (ch1,ch2)
    b[biagram] = b.get(biagram,0)+1


In [ ]:
b

{('.', 'e'): 1531,
 ('e', 'm'): 769,
 ('m', 'm'): 168,
 ('m', 'a'): 2590,
 ('a', '.'): 6640,
 ('.', 'o'): 394,
 ('o', 'l'): 619,
 ('l', 'i'): 2480,
 ('i', 'v'): 269,
 ('v', 'i'): 911,
 ('i', 'a'): 2445,
 ('.', 'a'): 4410,
 ('a', 'v'): 834,
 ('v', 'a'): 642,
 ('.', 'i'): 591,
 ('i', 's'): 1316,
 ('s', 'a'): 1201,
 ('a', 'b'): 541,
 ('b', 'e'): 655,
 ('e', 'l'): 3248,
 ('l', 'l'): 1345,
 ('l', 'a'): 2623,
 ('.', 's'): 2055,
 ('s', 'o'): 531,
 ('o', 'p'): 95,
 ('p', 'h'): 204,
 ('h', 'i'): 729,
 ('.', 'c'): 1542,
 ('c', 'h'): 664,
 ('h', 'a'): 2244,
 ('a', 'r'): 3264,
 ('r', 'l'): 413,
 ('l', 'o'): 692,
 ('o', 't'): 118,
 ('t', 't'): 374,
 ('t', 'e'): 716,
 ('e', '.'): 3983,
 ('.', 'm'): 2538,
 ('m', 'i'): 1256,
 ('a', 'm'): 1634,
 ('m', 'e'): 818,
 ('.', 'h'): 874,
 ('r', 'p'): 14,
 ('p', 'e'): 197,
 ('e', 'r'): 1958,
 ('r', '.'): 1377,
 ('e', 'v'): 463,
 ('v', 'e'): 568,
 ('l', 'y'): 1588,
 ('y', 'n'): 1826,
 ('n', '.'): 6763,
 ('b', 'i'): 217,
 ('i', 'g'): 428,
 ('g', 'a'): 330,
 ('a',

In [ ]:
sorted(b.items(),key = lambda kv:kv[1], reverse=True)

[(('n', '.'), 6763),
 (('a', '.'), 6640),
 (('a', 'n'), 5438),
 (('.', 'a'), 4410),
 (('e', '.'), 3983),
 (('a', 'r'), 3264),
 (('e', 'l'), 3248),
 (('r', 'i'), 3033),
 (('n', 'a'), 2977),
 (('.', 'k'), 2963),
 (('l', 'e'), 2921),
 (('e', 'n'), 2675),
 (('l', 'a'), 2623),
 (('m', 'a'), 2590),
 (('.', 'm'), 2538),
 (('a', 'l'), 2528),
 (('i', '.'), 2489),
 (('l', 'i'), 2480),
 (('i', 'a'), 2445),
 (('.', 'j'), 2422),
 (('o', 'n'), 2411),
 (('h', '.'), 2409),
 (('r', 'a'), 2356),
 (('a', 'h'), 2332),
 (('h', 'a'), 2244),
 (('y', 'a'), 2143),
 (('i', 'n'), 2126),
 (('.', 's'), 2055),
 (('a', 'y'), 2050),
 (('y', '.'), 2007),
 (('e', 'r'), 1958),
 (('n', 'n'), 1906),
 (('y', 'n'), 1826),
 (('k', 'a'), 1731),
 (('n', 'i'), 1725),
 (('r', 'e'), 1697),
 (('.', 'd'), 1690),
 (('i', 'e'), 1653),
 (('a', 'i'), 1650),
 (('.', 'r'), 1639),
 (('a', 'm'), 1634),
 (('l', 'y'), 1588),
 (('.', 'l'), 1572),
 (('.', 'c'), 1542),
 (('.', 'e'), 1531),
 (('j', 'a'), 1473),
 (('r', '.'), 1377),
 (('n', 'e'),

In [ ]:
for i in enumerate(range(50,100)):
  print(i)


(0, 50)
(1, 51)
(2, 52)
(3, 53)
(4, 54)
(5, 55)
(6, 56)
(7, 57)
(8, 58)
(9, 59)
(10, 60)
(11, 61)
(12, 62)
(13, 63)
(14, 64)
(15, 65)
(16, 66)
(17, 67)
(18, 68)
(19, 69)
(20, 70)
(21, 71)
(22, 72)
(23, 73)
(24, 74)
(25, 75)
(26, 76)
(27, 77)
(28, 78)
(29, 79)
(30, 80)
(31, 81)
(32, 82)
(33, 83)
(34, 84)
(35, 85)
(36, 86)
(37, 87)
(38, 88)
(39, 89)
(40, 90)
(41, 91)
(42, 92)
(43, 93)
(44, 94)
(45, 95)
(46, 96)
(47, 97)
(48, 98)
(49, 99)


In [ ]:
list1 = ['hello','my','name']
final = ' '.join(list1)

In [ ]:
final

'hello my name'

In [ ]:
''.join(content)

'emmaoliviaavaisabellasophiacharlottemiaameliaharperevelynabigailemilyelizabethmilaellaaverysofiacamilaariascarlettvictoriamadisonlunagracechloepenelopelaylarileyzoeynoralilyeleanorhannahlillianaddisonaubreyelliestellanataliezoeleahhazelvioletaurorasavannahaudreybrooklynbellaclaireskylarlucypaisleyeverlyannacarolinenovagenesisemiliakennedysamanthamayawillowkinsleynaomiaaliyahelenasaraharianaallisongabriellaalicemadelyncorarubyevaserenityautumnadelinehaileygiannavalentinaislaelianaquinnnevaehivysadiepiperlydiaalexajosephineemeryjuliadelilahariannaviviankayleesophiebriellemadelinepeytonryleeclarahadleymelaniemackenziereaganadalynnlilianaaubreejadekatherineisabellenataliaraelynnmariaathenaximenaaryaleilanitaylorfaithrosekyliealexandramarymargaretlylaashleyamayaelizabriannabaileyandreakhloejasminemelodyirisisabelnorahannabellevaleriaemersonadalynryleighedenemersynanastasiakaylaalyssajulianacharlieestherarielceciliavaleriealinamollyreesealiyahlillyparkerfinleymorgansydneyjordyneloisetrinity

In [ ]:
chars = set(''.join(content))

In [ ]:
chars

{'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z'}

In [ ]:
mapping = {char:index+1 for index,char in enumerate(sorted(chars))}

In [ ]:
mapping_1 = mapping

In [ ]:
mapping_1['.'] = 0

In [ ]:
mapping_2 = {index+1:char for index, char in enumerate(sorted(set(''.join(content))))}

In [ ]:
mapping_2[0] = '.'

In [ ]:
mapping_1

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [ ]:
mapping_2

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [ ]:
import torch

In [ ]:
N = torch.zeros((27,27),dtype=torch.int)

In [ ]:
N

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],


In [ ]:
for word in content:
  chs = ['.'] + list(word) + ['.']
  # print(chs[1:])
  for ch1, ch2 in zip(chs,chs[1:]):
    # print(ch1,ch2)
    i1 = mapping[ch1]
    i2 = mapping[ch2]
    N[i1,i2] +=1
    # biagram = (ch1,ch2)
    # b[biagram] = b.get(biagram,0)+1


In [ ]:
# b= {}
for word in content[:1]:
  chs = ['.'] + list(word) + ['.']
  # print(chs[1:])
  for ch1, ch2 in zip(chs,chs[1:]):
    print(ch1,ch2)
    # i1 = mapping_1[ch1]
    # i2 = mapping_1[ch2]
    # N[i1,i2] +=1
    # biagram = (ch1,ch2)
    # b[biagram] = b.get(biagram,0)+1


. e
e m
m m
m a
a .


In [ ]:
N

tensor([[   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
         1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
          134,  535,  929],
        [6640,  556,  541,  470, 1042,  692,  134,  168, 2332, 1650,  175,  568,
         2528, 1634, 5438,   63,   82,   60, 3264, 1118,  687,  381,  834,  161,
          182, 2050,  435],
        [ 114,  321,   38,    1,   65,  655,    0,    0,   41,  217,    1,    0,
          103,    0,    4,  105,    0,    0,  842,    8,    2,   45,    0,    0,
            0,   83,    0],
        [  97,  815,    0,   42,    1,  551,    0,    2,  664,  271,    3,  316,
          116,    0,    0,  380,    1,   11,   76,    5,   35,   35,    0,    0,
            3,  104,    4],
        [ 516, 1303,    1,    3,  149, 1283,    5,   25,  118,  674,    9,    3,
           60,   30,   31,  378,    0,    1,  424,   29,    4,   92,   17,   23,
            0,  317,    1],
        [3983,  679,  121,  153,  384, 1271,   82,

In [ ]:
N[0,:]

tensor([   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
        1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
         134,  535,  929], dtype=torch.int32)

In [ ]:
p = N[0,:].float()

In [ ]:
p  = p/p.sum()

In [ ]:
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [ ]:
import torch

In [ ]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3,generator=g)
p = p/p.sum()

In [ ]:
p

tensor([0.6064, 0.3033, 0.0903])

In [ ]:
torch.multinomial(p,num_samples=20,replacement=True,generator=g)

tensor([0, 2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1])

In [ ]:
p = N[0].float()
p = p/p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [ ]:
ix = torch.multinomial(p,num_samples=1,replacement=True,generator=g).item()
mapping_2[ix]

'h'

In [ ]:
g = torch.Generator().manual_seed(2147483647)


final = []
for i in range(10):
  out=[]
  ix=0
  while True:
    p = N[ix].float()
    p = p/p.sum()
    ix = torch.multinomial(p,num_samples=1,replacement=True,generator=g).item()
    # print(mapping_2[ix])
    out.append(mapping_2[ix])
    if ix==0:
      break

  final.append(''.join(out))
  print(''.join(out))




junide.
janasah.
p.
cony.
a.
nn.
kohin.
tolian.
juee.
ksahnaauranilevias.


In [ ]:
print(out)

['k', 's', 'a', 'h', 'n', 'a', 'a', 'u', 'r', 'a', 'n', 'i', 'l', 'e', 'v', 'i', 'a', 's', '.']


In [ ]:
print(final)

['junide.', 'janasah.', 'p.', 'cony.', 'a.', 'nn.', 'kohin.', 'tolian.', 'juee.', 'ksahnaauranilevias.']


In [ ]:
p = (N+1).float()

In [ ]:
p = p/p.sum(1,keepdim=True)

In [ ]:
p

tensor([[3.1192e-05, 1.3759e-01, 4.0767e-02, 4.8129e-02, 5.2745e-02, 4.7785e-02,
         1.3038e-02, 2.0898e-02, 2.7293e-02, 1.8465e-02, 7.5577e-02, 9.2452e-02,
         4.9064e-02, 7.9195e-02, 3.5777e-02, 1.2321e-02, 1.6095e-02, 2.9008e-03,
         5.1154e-02, 6.4130e-02, 4.0830e-02, 2.4641e-03, 1.1759e-02, 9.6070e-03,
         4.2109e-03, 1.6719e-02, 2.9008e-02],
        [1.9583e-01, 1.6425e-02, 1.5983e-02, 1.3889e-02, 3.0756e-02, 2.0435e-02,
         3.9809e-03, 4.9835e-03, 6.8796e-02, 4.8685e-02, 5.1899e-03, 1.6779e-02,
         7.4575e-02, 4.8213e-02, 1.6039e-01, 1.8872e-03, 2.4475e-03, 1.7988e-03,
         9.6279e-02, 3.2997e-02, 2.0288e-02, 1.1264e-02, 2.4623e-02, 4.7771e-03,
         5.3963e-03, 6.0480e-02, 1.2857e-02],
        [4.3039e-02, 1.2051e-01, 1.4596e-02, 7.4850e-04, 2.4701e-02, 2.4551e-01,
         3.7425e-04, 3.7425e-04, 1.5719e-02, 8.1587e-02, 7.4850e-04, 3.7425e-04,
         3.8922e-02, 3.7425e-04, 1.8713e-03, 3.9671e-02, 3.7425e-04, 3.7425e-04,
         3.1549e-

In [ ]:
g = torch.Generator().manual_seed(2147483647)


final = []
for i in range(10):
  out=[]
  ix=0
  while True:
    p_calc = p[ix]
    ix = torch.multinomial(p_calc,num_samples=1,replacement=True,generator=g).item()
    # print(mapping_2[ix])
    out.append(mapping_2[ix])
    if ix==0:
      break

  final.append(''.join(out))
  print(''.join(out))




junide.
janasah.
p.
cony.
a.
nn.
kohin.
tolian.
juee.
ksahnaauranilevias.


In [ ]:
p[0,1]

tensor(0.1376)

In [ ]:
log_likelihood = 0
count = 0
name = ['vedantq']
for word in name:
  chs = ['.'] + list(word) + ['.']
  # print(chs[1:])
  for ch1, ch2 in zip(chs,chs[1:]):
    # print(ch1,ch2)
    i1 = mapping[ch1]
    i2 = mapping[ch2]
    # print([i1,i2]
    # print(p[i1,i2]) )
    prob = p[i1,i2]
    logprob = torch.log(prob)
    log_likelihood+=logprob
    count+=1

    print(f'{ch1} {ch2} : {prob: .4f} ,     logliklihood:   {logprob: .4f}')
    # biagram = (ch1,ch2)
    # b[biagram] = b.get(biagram,0)+1
print(f'the liklihood:{log_likelihood}')
nll = -log_likelihood
print(nll/count)

. v :  0.0118 ,     logliklihood:   -4.4431
v e :  0.2188 ,     logliklihood:   -1.5194
e d :  0.0188 ,     logliklihood:   -3.9725
d a :  0.2361 ,     logliklihood:   -1.4435
a n :  0.1604 ,     logliklihood:   -1.8302
n t :  0.0242 ,     logliklihood:   -3.7218
t q :  0.0002 ,     logliklihood:   -8.6300
q . :  0.0970 ,     logliklihood:   -2.3331
the liklihood:-27.893569946289062
tensor(3.4867)


training set for the whole set

In [ ]:
xs = []
ys = []
for word in content:
  chs = ['.'] + list(word) + ['.']
  for ch1, ch2 in zip(chs,chs[1:]):
    ix1 = mapping_1[ch1]
    ix2 = mapping_1[ch2]
    # print(ix1,ix2)
    # print(ch1,ch2)
    # print(f'the prob related to their occurence:{p[ix1,ix2]}')
    xs.append(ix1)
    ys.append(ix2)
xs = torch.tensor(xs)
ys = torch.tensor(ys)

In [ ]:
xs.size()

torch.Size([228146])

In [ ]:
ys

tensor([ 5, 13, 13,  ..., 26, 24,  0])

In [ ]:
import torch.nn.functional as F

In [ ]:
xenc = F.one_hot(xs, num_classes=27).float()

In [ ]:
xenc.shape

torch.Size([228146, 27])

In [ ]:
xenc

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 1., 0., 0.]])

In [ ]:
w = torch.randn((27,27))

In [ ]:
w

tensor([[-1.3069, -0.2407, -1.9381, -0.0291,  0.3674, -0.7515, -0.8652,  1.5600,
         -1.2073,  0.0696,  1.2155, -0.7190, -0.4096, -0.5555, -0.3971, -0.8438,
         -1.8001,  1.4130, -0.4204, -0.9063, -0.2608,  0.6413,  0.2321,  1.8311,
          0.0064,  0.7450, -1.3100],
        [-1.1319, -0.4112, -1.4645, -0.4331,  0.5449, -0.1810, -1.3865, -1.3602,
         -1.0314,  0.2406,  1.5762, -0.3615,  0.3906, -0.4297,  0.4500,  0.8918,
          0.7971, -2.3422, -0.7487,  0.6848, -0.0110,  0.1574,  0.2314, -0.6398,
          0.2238,  0.6005,  1.2032],
        [-0.7270, -0.5335, -0.7498,  0.6396, -0.4411, -0.8483, -0.1498,  1.1111,
          0.3141, -1.6577, -1.2139, -0.0745,  0.0063, -0.0300,  0.2292, -0.9170,
          0.9118,  0.6499, -0.8037, -0.5974,  1.2691,  0.0795,  0.3610,  0.6287,
          0.6489,  0.6343, -2.2264],
        [-1.4116, -0.8948, -1.1952,  0.7592, -1.0021, -1.0264, -0.1227, -0.5927,
         -0.3401, -1.2743,  0.2415,  0.6343, -1.1687, -0.4653, -1.3643,  0.9945

In [ ]:
logits = (xenc @ w)
count = logits.exp()
count.shape
# count.shape
prob = count/count.sum(1,keepdims=True)
prob.shape

torch.Size([5, 27])

In [ ]:
prob[0]

tensor([0.0187, 0.0597, 0.0079, 0.0084, 0.0062, 0.0387, 0.0905, 0.0151, 0.0784,
        0.0156, 0.0156, 0.1233, 0.0224, 0.0493, 0.0200, 0.0233, 0.0156, 0.0081,
        0.0627, 0.0335, 0.0896, 0.0650, 0.0782, 0.0289, 0.0072, 0.0053, 0.0127])

In [ ]:
xs[3]

tensor(13)

using a generator

In [ ]:
g = torch.Generator().manual_seed(2147483647)
w = torch.randn(27,27,generator=g)

In [ ]:
xs

tensor([ 0,  5, 13, 13,  1])

In [ ]:
loss = torch.zeros(5)
for i in range(5):
  x = xs[i].item()
  y = ys[i].item()
  #loss
  p = prob[i,y]
  # print(p.item())
  # print(prob[x].sum().item())
  logp = torch.log(p)
  loss[i] = -logp
loss.mean().item()





3.7693049907684326

gradients

In [ ]:
g = torch.Generator().manual_seed(2147483647)
w = torch.randn((27,27),generator=g,requires_grad=True)

In [ ]:
w

tensor([[ 1.5674e+00, -2.3729e-01, -2.7385e-02, -1.1008e+00,  2.8588e-01,
         -2.9643e-02, -1.5471e+00,  6.0489e-01,  7.9136e-02,  9.0462e-01,
         -4.7125e-01,  7.8682e-01, -3.2843e-01, -4.3297e-01,  1.3729e+00,
          2.9334e+00,  1.5618e+00, -1.6261e+00,  6.7716e-01, -8.4039e-01,
          9.8488e-01, -1.4837e-01, -1.4795e+00,  4.4830e-01, -7.0730e-02,
          2.4968e+00,  2.4448e+00],
        [-6.7006e-01, -1.2199e+00,  3.0314e-01, -1.0725e+00,  7.2762e-01,
          5.1114e-02,  1.3095e+00, -8.0220e-01, -8.5042e-01, -1.8068e+00,
          1.2523e+00, -1.2256e+00,  1.2165e+00, -9.6478e-01, -2.3211e-01,
         -3.4762e-01,  3.3244e-01, -1.3263e+00,  1.1224e+00,  5.9641e-01,
          4.5846e-01,  5.4011e-02, -1.7400e+00,  1.1560e-01,  8.0319e-01,
          5.4108e-01, -1.1646e+00],
        [ 1.4756e-01, -1.0006e+00,  3.8012e-01,  4.7328e-01, -9.1027e-01,
         -7.8305e-01,  1.3506e-01, -2.1161e-01, -1.0406e+00, -1.5367e+00,
          9.3743e-01, -8.8303e-01,  1.74

In [ ]:
import torch.optim as optim

In [ ]:
optimizer = optim.SGD([w],lr=0.05)

In [ ]:
# print(f'{logits[0,0].item(): .4f}')

In [ ]:
# loss = torch.zeros(100,requires_grad=True)
for epoch in range(100):
  # loss = torch.zeros(100,requires_grad=True)

  # x = xs[i].item()
  # y = ys[i].item()

  logits = (xenc @ w)
  logged = logits.exp()
  prob = logged/logged.sum(1,keepdims=True)
  # print(prob.shape)
  # print(xs.shape,ys.shape)
  # break
  loss = -prob[torch.arange(xs.numel()).reshape(xs.shape),ys].log().mean()
  # # print(prob)
  # # print(prob.shape)
  # # break
  # loss_iter = 0
  # for i in range(prob.size(0)):
  #   x = xs[i].item()
  #   y = ys[i].item()
  #   l_1 = -prob[i,y]
  #   loss_iter += torch.log(l_1)
  # loss[epoch] = loss_iter.item()
  if (epoch+1)%10==0:
    print(f'the loss at {epoch+1}:{loss.item()}')
  loss.backward()
  optimizer.step()
  optimizer.zero_grad()


the loss at 10:3.754852056503296
the loss at 20:3.750319719314575
the loss at 30:3.7458128929138184
the loss at 40:3.7413320541381836
the loss at 50:3.7368767261505127
the loss at 60:3.7324464321136475
the loss at 70:3.728041172027588
the loss at 80:3.723660469055176
the loss at 90:3.719304084777832
the loss at 100:3.7149720191955566


In [ ]:
print(loss.item())

3.6330747604370117


In [ ]:
 # w -= w.grad*0.01

In [ ]:
import torch
import torch.optim as optim

# Assuming xenc, xs, and ys are defined somewhere in your code

g = torch.Generator().manual_seed(2147483647)
w = torch.randn((27, 27), generator=g, requires_grad=True)

optimizer = optim.SGD([w], lr=0.01)

for epoch in range(100):
    # Create a new loss tensor for each epoch
    loss = torch.zeros(100, requires_grad=True)

    logits = torch.matmul(xenc, w)
    logged = logits.exp()
    prob = logged / logged.sum(1, keepdims=True)

    for i in range(prob.size(0)):
        x = xs[i].item()
        y = ys[i].item()
        l_1 = -prob[i, y]
        loss[i] = torch.log(l_1+1e-12)

        if (i + 1) % 10 == 0:
            print(f'The loss at epoch {epoch + 1}, iteration {i + 1}: {loss[i].item()}')

    # Calculate the average loss for the epoch
    average_loss = loss.mean()

    # Backward pass and optimization step
    average_loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    print(f'Epoch {epoch + 1}, Average loss: {average_loss.item()}')


RuntimeError: ignored

In [ ]:
import torch
import torch.optim as optim

# Assuming xenc, xs, and ys are defined somewhere in your code

g = torch.Generator().manual_seed(2147483647)
w = torch.randn((27, 27), generator=g, requires_grad=True)

optimizer = optim.SGD([w], lr=0.01)

for epoch in range(100):
    # Create a new loss tensor for each epoch
    loss_values = []

    logits = torch.matmul(xenc, w)
    logged = logits.exp()
    prob = logged / logged.sum(1, keepdim=True)

    for i in range(prob.size(0)):
        x = xs[i].item()
        y = ys[i].item()
        l_1 = -prob[i, y]
        loss_values.append(torch.log(l_1 + 1e-12))  # Added a small epsilon to avoid log(0)

        # if (i + 1) % 10 == 0:
        #     print(f'The loss at epoch {epoch + 1}, iteration {i + 1}: {loss_values[-1].item()}')

    # Create a new tensor to store the losses
    loss = torch.stack(loss_values)

    # Calculate the average loss for the epoch
    average_loss = loss.mean()

    # Backward pass and optimization step
    average_loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    print(f'Epoch {epoch + 1}, Average loss: {average_loss.item()}')


In [ ]:
prob[torch.arange(5),ys]


IndexError: ignored

In [ ]:
import torch
import torch.optim as optim
import torch.nn.functional as F

In [ ]:
g = torch.Generator().manual_seed(2147483647)
w = torch.randn((27,27),generator=g,requires_grad=True)
optimizer = optim.SGD([w],lr=0.2)

In [ ]:
ys

tensor([ 5, 13, 13,  ..., 26, 24,  0])

In [ ]:
# losses = []
for epoch in range(100):
  # x = xs[epoch].item()
  # y = ys[epoch].item()
  logits = torch.matmul(xenc,w)
  probs = F.softmax(logits,dim=1)
  # print(probs)
  # break
  loss_i = F.nll_loss(torch.log(probs),ys)
  # losses.append(loss_i)
  loss_i.backward()
  optimizer.step()
  optimizer.zero_grad()
  if (epoch + 1) % 10 == 0:
        print(f'The loss at epoch {epoch + 1}: {loss_i.item()}')



The loss at epoch 10: 3.58164381980896
The loss at epoch 20: 3.567303419113159
The loss at epoch 30: 3.5532479286193848
The loss at epoch 40: 3.5394704341888428
The loss at epoch 50: 3.5259640216827393
The loss at epoch 60: 3.5127224922180176
The loss at epoch 70: 3.499739646911621
The loss at epoch 80: 3.4870100021362305
The loss at epoch 90: 3.4745285511016846
The loss at epoch 100: 3.4622888565063477


In [ ]:
probs

tensor([[0.0617, 0.0116, 0.0133,  ..., 0.0125, 0.1486, 0.1431],
        [0.0318, 0.0795, 0.0251,  ..., 0.0120, 0.0022, 0.0473],
        [0.0315, 0.0776, 0.0484,  ..., 0.1186, 0.0470, 0.0127],
        ...,
        [0.0318, 0.0085, 0.0092,  ..., 0.0127, 0.0535, 0.0113],
        [0.0635, 0.0275, 0.0101,  ..., 0.0831, 0.0176, 0.0516],
        [0.0309, 0.0113, 0.0178,  ..., 0.0191, 0.0117, 0.0562]],
       grad_fn=<SoftmaxBackward0>)

In [ ]:
torch.log(probs)

tensor([[-2.7853, -4.4574, -4.3169,  ..., -4.3855, -1.9067, -1.9443],
        [-3.4471, -2.5321, -3.6858,  ..., -4.4246, -6.0981, -3.0517],
        [-3.4579, -2.5561, -3.0291,  ..., -2.1316, -3.0583, -4.3691],
        ...,
        [-3.4479, -4.7703, -4.6939,  ..., -4.3684, -2.9289, -4.4862],
        [-2.7571, -3.5929, -4.5908,  ..., -2.4883, -4.0394, -2.9633],
        [-3.4781, -4.4828, -4.0279,  ..., -3.9600, -4.4523, -2.8789]],
       grad_fn=<LogBackward0>)

In [ ]:
mapping_1

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [ ]:
print(w)

tensor([[ 1.5674e+00, -2.3729e-01, -2.7385e-02, -1.1008e+00,  2.8588e-01,
         -2.9643e-02, -1.5471e+00,  6.0489e-01,  7.9136e-02,  9.0462e-01,
         -4.7125e-01,  7.8682e-01, -3.2843e-01, -4.3297e-01,  1.3729e+00,
          2.9334e+00,  1.5618e+00, -1.6261e+00,  6.7716e-01, -8.4039e-01,
          9.8488e-01, -1.4837e-01, -1.4795e+00,  4.4830e-01, -7.0730e-02,
          2.4968e+00,  2.4448e+00],
        [-6.7006e-01, -1.2199e+00,  3.0314e-01, -1.0725e+00,  7.2762e-01,
          5.1114e-02,  1.3095e+00, -8.0220e-01, -8.5042e-01, -1.8068e+00,
          1.2523e+00, -1.2256e+00,  1.2165e+00, -9.6478e-01, -2.3211e-01,
         -3.4762e-01,  3.3244e-01, -1.3263e+00,  1.1224e+00,  5.9641e-01,
          4.5846e-01,  5.4011e-02, -1.7400e+00,  1.1560e-01,  8.0319e-01,
          5.4108e-01, -1.1646e+00],
        [ 1.4756e-01, -1.0006e+00,  3.8012e-01,  4.7328e-01, -9.1027e-01,
         -7.8305e-01,  1.3506e-01, -2.1161e-01, -1.0406e+00, -1.5367e+00,
          9.3743e-01, -8.8303e-01,  1.74

In [ ]:
xenc

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 1., 0., 0.]])

In [ ]:
xs

tensor([ 0,  5, 13,  ..., 25, 26, 24])

In [ ]:
ls = []
for i in name:
  ls.append(mapping_1[i])
print(ls)
ls=torch.tensor(ls)
encoded = F.one_hot(ls,num_classes=27)

[22, 5, 4, 1, 14, 20]


In [ ]:
encoded.dtype

torch.float32

In [ ]:
encoded = torch.tensor(encoded,dtype=torch.float32)

<ipython-input-98-2a8401f4b3dd>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  encoded = torch.tensor(encoded,dtype=torch.float32)


In [ ]:
name = "vedant"



logits = torch.matmul(encoded,w)
# print(logits.shape)
probs = F.softmax(logits,dim=1)


  # probs = F.softmax(logits)
  # ix1 = mapping_1[ch1]
  # ix2 = mapping_1[ch2]
  # prob = w[ix1,ix2]
  # final.append()
  # print(f'{ch1, ch2}:{prob}')



tensor(0.1633, grad_fn=<MaxBackward1>)
tensor(0.1989, grad_fn=<MaxBackward1>)
tensor(0.1240, grad_fn=<MaxBackward1>)
tensor(0.1084, grad_fn=<MaxBackward1>)
tensor(0.1556, grad_fn=<MaxBackward1>)
tensor(0.2312, grad_fn=<MaxBackward1>)


In [ ]:
for epoch in range(100):
  logits = torch.matmul(encoded,w)
  probs = F.softmax(probs,dim=1)